/*********************************
ECEN5003 Project 2
Module 4 : Harmonic Analysis

Write a program either using the mbed compiler, or in the Keil MDK, to read
a 1004 Hz tone from a file into the ADC buffer and perform a harmonic 
analysis.  Use the samples from your .csv or .txt file from the previous
question for the input to the analyzer. (NOTE: we prefer you do not use arrays
to input values from your csv file to your program. Better to create a lookup
table in the debug tool, or use a serial port transfer program to read the
file data into your target program). 

Bonus Points: Using the on chip ADC, read in a 1004 Hz tone generated by a
function generator in the lab or in ITLL. Perform a harmonic analysis on this input data.
**********************************/

#include "mbed.h"

DigitalOut led(LED1);
Serial serial(USBTX, USBRX);

char buf[1000];
unsigned short buf_pos = 0;
volatile unsigned int count = 0;
volatile char done = 0;
float ts[5000];
short vals[5000];


void reader(void) {
  char c;
  float t;
  short val;
  while(serial.readable()) {
    c = serial.getc();
    //serial.putc(c);
    buf[buf_pos++] = c;
    if( (c == '\n') || (c == '\r') ) {
      buf[buf_pos-1] = '\0';
      //printf("Got: '%s'\n", buf);
      sscanf(buf, "%f %hx", &t, &val);
      if( (t>=0) && (!done) ) {
        ts[count] = t;      
        vals[count] = val;
        count++;
      } else {
        done = 1;
      }
      //printf("%0.5f %04hx\n", t, val);
      buf_pos = 0;
    }
  }
}

int main() {
  serial.baud(57600);
  printf("* Reset *\n");
  printf("Waiting for input file...\n");
  serial.attach(reader, Serial::RxIrq);
  
  while(!done) {
    wait_ms(200);
    led = !led;
  }
  printf("Read %d samples\n", count);
  for(int i=0; i<count; i++) {
    printf("%0.5f %04hx\n", ts[i], vals[i]);
  }
  
  while(1);
}
